{% set name = "cement" %}
{% set version = "3.0.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fccec41eab3f15a03445b1ce24c8a7e106d4d5520f6507a7145698ce68923d31

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - cement = cement.cli.main:main


requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6

test:
  imports:
    - cement
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://builtoncement.com
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: CLI Application Framework for Python
  doc_url: http://builtoncement.com/2.6/
  dev_url: https://github.com/datafolklabs/cement

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
