{% set name = "cement" %}
{% set version = "2.10.12" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "58efb4eacd9ec977ce797a364a13851de6e42392bbde5287d44294f06c5a2f70" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}
build:
  preserve_egg_dir: True
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  imports:
    - cement
    - cement.core
    - cement.ext
    - cement.utils
    - examples

about:
  home: http://builtoncement.com
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'CLI Application Framework for Python'
  doc_url: http://builtoncement.com/2.6/
  dev_url: https://github.com/datafolklabs/cement

extra:
  recipe-maintainers:
    - pmlandwehr
