travis:
  secure:
    BINSTAR_TOKEN: arnjn+InKhdjv9XSeuw3muot6l5YQ7YPrPXnxog7c+Ib+fz4SWExbfbbftAJPB99RRxtwnXO52MZQDeKP9JN4rNJa6AodIPMPM6J1hzR2FgRdKtJ6DKQd6om/gNkBt8ceTdQZZEwADJezP8XZ03UcbWj0aGlurqwiiVBnvhPkKfaclKMjdXAB9kZ4l9DWZ+iOTFa5cRfaDRm1zaHPJuOj2Te6H/cnUWwVLvAqdhfLzw4oO1/evm+1MYn11efeBPrqoIt9zgsFPDIn80idiIjfkWkh1L+y6L28tENNnzn1aXACfobQszy33mR2lg0X2UAHLkH7FysSlv2DgeZQPnGEJazRsNbYsDIygPvQUGE8EbunfNUZPJmA7jpQwc3hC5caTyYgiSg9rqIBRnnoASz6e4AxYmwSzsLIDM3DV4xjaBqBqSbYURjF2hg6TXjLqWzXX6nCCf+AACBL7BRGbfdqtCRf/56BoIdy8ZI4gqru3g5IfolBga8CP0Aziw0V2ERzf4Tn+qHkJgABaEzKbD2euw2lvWWOruSpj5GnuiZzgjrcj6bB7eBLK1386FhAFxxQP2nxQLxHWClmJw7/H1lWicKuoYgKBnNpR+usRAG26VOZJfFpDiCKMzkUbCqB1UAqMCfDAyTaFz0g6txaJDDGolyNzGC78MvSISSUndEQ+s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
