travis:
  secure:
    BINSTAR_TOKEN: eSezbc7/bUgmgCbaWrnKEA/5BOzbEpxJ+4XwiTd9RSUoHj9iSZj/xIIy3x37kY9u3iW9KDJ1focL/PKahOUeC5z9/SEunT3zwqf/Xfj+2G0w+79VtAh8vzxHF7wMCmilKKuIQXZmtvY/OvznbnoM1eGuodiKMJBfkP37QlFLiM/wRIfZKwex/CO+pkTfl5K7t9tAtXKmgVd4CYk7a0JUR75eecNDkiwoHzNIEsuG8HzcLvAJwE0hV6hCTfZCVY+9sazXCeeU3k3sQ6r9SAQ5BurECg6PtLvB3KXEzpGJKQGbjGp5wWHg5FoOCrirwa01Wv0zALBbvVa5+y225qB1aAiLjjEzFgThPzEpIVXXLjiFd1+kwoiLP/o9bAIO47tKgggcIp6IbDWRyB/nYQhQrTZtF4YbXO6iNhG+0XwmY324w7Eaj2hLN4+jRjiJR/RXOCAHsNnQKaIJl4omlMg0VecKJvp0W3p++YfgiY2RMhIaDVqiHZ82iVPNB9alnG0RVvI/xHGJwgZiAeKvGHi4DbqsDbKxJTBE/zAKIVN3PFPgpO60wePzx5AnQGV39cTvBH16+0cTVS02wZCYQXogrZ7LyZjRUT32J1vot9yJ5I7cbBWDaxoGIZZmq4KMiE3VC25IOWoPz7fwi+mfoeaLbb2NvYJYh0hQ1T3RzwC4MZY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
